=== Bigcheese/l2adena-l2j-datapack/languages/accountmanager/accountmanager.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="localization">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="1">
				<xs:element name="message" minOccurs="1" maxOccurs="30">
					<xs:complexType>
						<xs:attribute name="id" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:token">
									<xs:enumeration value="falseString" />
									<xs:enumeration value="functAccessLevel" />
									<xs:enumeration value="functAccessLevelNotExist" />
									<xs:enumeration value="functAccessLevelUpdated" />
									<xs:enumeration value="functChooser" />
									<xs:enumeration value="functCreateAccount"></xs:enumeration>
									<xs:enumeration value="functDeleteAccount" />
									<xs:enumeration value="functDeleteAccountAbort" />
									<xs:enumeration value="functDeleteAccountCancel" />
									<xs:enumeration value="functDeleteAccountChar" />
									<xs:enumeration value="functDeleteAccountClan" />
									<xs:enumeration value="functDeleteAccountComplete" />
									<xs:enumeration value="functDeleteAccountConfirm" />
									<xs:enumeration value="functDeleteAccountNotExist" />
									<xs:enumeration value="functExit" />
									<xs:enumeration value="functListAccount" />
									<xs:enumeration value="functListAccountAll" />
									<xs:enumeration value="functListAccountBanned" />
									<xs:enumeration value="functListAccountChooser" />
									<xs:enumeration value="functListAccountDisplayed" />
									<xs:enumeration value="functListAccountPrivileged" />
									<xs:enumeration value="functListAccountRegular" />
									<xs:enumeration value="inputAccessLevel" />
									<xs:enumeration value="inputChoice" />
									<xs:enumeration value="inputPassword" />
									<xs:enumeration value="inputUsername" />
									<xs:enumeration value="noChar" />
									<xs:enumeration value="toolName" />
									<xs:enumeration value="trueString" />
									<xs:enumeration value="yesChar" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="text" type="xs:normalizedString" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="extends" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:language">
						<xs:enumeration value="ar" />
						<xs:enumeration value="ar" />
						<xs:enumeration value="be" />
						<xs:enumeration value="ca" />
						<xs:enumeration value="cs" />
						<xs:enumeration value="da" />
						<xs:enumeration value="de" />
						<xs:enumeration value="el" />
						<xs:enumeration value="en" />
						<xs:enumeration value="es" />
						<xs:enumeration value="et" />
						<xs:enumeration value="fi" />
						<xs:enumeration value="fr" />
						<xs:enumeration value="ga" />
						<xs:enumeration value="hi" />
						<xs:enumeration value="hr" />
						<xs:enumeration value="hu" />
						<xs:enumeration value="in" />
						<xs:enumeration value="is" />
						<xs:enumeration value="it" />
						<xs:enumeration value="iw" />
						<xs:enumeration value="ja" />
						<xs:enumeration value="ko" />
						<xs:enumeration value="lt" />
						<xs:enumeration value="lv" />
						<xs:enumeration value="mk" />
						<xs:enumeration value="ms" />
						<xs:enumeration value="mt" />
						<xs:enumeration value="nl" />
						<xs:enumeration value="no" />
						<xs:enumeration value="pl" />
						<xs:enumeration value="pt" />
						<xs:enumeration value="ro" />
						<xs:enumeration value="ru" />
						<xs:enumeration value="sk" />
						<xs:enumeration value="sl" />
						<xs:enumeration value="sq" />
						<xs:enumeration value="sr" />
						<xs:enumeration value="sv" />
						<xs:enumeration value="th" />
						<xs:enumeration value="tr" />
						<xs:enumeration value="uk" />
						<xs:enumeration value="vi" />
						<xs:enumeration value="zh" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="lang" type="xs:normalizedString" use="required" />
			<xs:attribute name="translator" type="xs:normalizedString" use="required" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Bigcheese/l2adena-l2j-datapack/languages/accountmanager/SQLAccountManager_pt.xml
<?xml version="1.0" encoding="UTF-8"?>
<localization lang="Portuguese" translator="UnHoly" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="accountmanager.xsd">
	<message id="toolName" text="Administrador de Contas SQL" />

	<message id="yesChar" text="s" />
	<message id="noChar" text="n" />
	<message id="trueString" text="True" />
	<message id="falseString" text="False" />

	<message id="functChooser" text="Selecione uma opção" />
	<message id="functCreateAccount" text="1 - Criar uma nova ou atualizar uma conta existente (alteração de senha e nível de acesso)" />
	<message id="functAccessLevel" text="2 - Alterar nível de acesso" />
	<message id="functDeleteAccount" text="3 - Excluir uma conta existente" />
	<message id="functListAccount" text="4 - Listar contas e níveis de acesso" />
	<message id="functExit" text="5 - Sair" />

	<message id="inputChoice" text="Escolha" />
	<message id="inputUsername" text="Nome de usuário" />
	<message id="inputPassword" text="Senha" />
	<message id="inputAccessLevel" text="Nível de acesso" />

	<message id="functListAccountChooser" text="Por favor selecione um modo de visualização" />
	<message id="functListAccountBanned" text="1 - Listar somente contas banidas (accessLevel &lt; 0)" />
	<message id="functListAccountPrivileged" text="2 - Listar contas de GM ou com privilégios de nível de acesso (accessLevel &gt; 0)" />
	<message id="functListAccountRegular" text="3 - Listar contas de usários (accessLevel = 0)" />
	<message id="functListAccountAll" text="4 - Listar todas as contas" />
	<message id="functListAccountDisplayed" text="Exibindo contas: %d" />

	<message id="functAccessLevelUpdated" text="A conta %s foi atualizada" />
	<message id="functAccessLevelNotExist" text="A conta %s não existe" />

	<message id="functDeleteAccountConfirm" text="Deseja realmente excluir esta conta ? S/N" />
	<message id="functDeleteAccountAbort" text="Exclusão abortada" />
	<message id="functDeleteAccountCancel" text="Exclusão cancelada" />
	<message id="functDeleteAccountChar" text="Excluir personagem %s" />
	<message id="functDeleteAccountClan" text="Excluir Clan %s" />
	<message id="functDeleteAccountComplete" text="A conta %s foi excluída" />
	<message id="functDeleteAccountNotExist" text="A conta %s não existe" />
</localization>

=== Bigcheese/l2adena-l2j-datapack/languages/accountmanager/SQLAccountManager_zhTW.xml
<?xml version="1.0" encoding="UTF-8"?>
<localization lang="Chinese (Taiwan)" translator="Labman" extends="zh" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="accountmanager.xsd">
	<message id="toolName" text="SQL 帳號管理" />

	<message id="yesChar" text="y" />
	<message id="noChar" text="n" />
	<message id="trueString" text="是" />
	<message id="falseString" text="否" />

	<message id="functChooser" text="請選一個您要的功能" />
	<message id="functCreateAccount" text="1 - 創立新帳號 或 變更已存在的帳號 (更改密碼與權限等級)" />
	<message id="functAccessLevel" text="2 - 變更權限等級" />
	<message id="functDeleteAccount" text="3 - 刪除已存在的帳號" />
	<message id="functListAccount" text="4 - 列出現有帳號 與 權限等級" />
	<message id="functExit" text="5 - 離開" />

	<message id="inputChoice" text="您的選擇" />
	<message id="inputUsername" text="使用者名稱" />
	<message id="inputPassword" text="密碼" />
	<message id="inputAccessLevel" text="權限等級" />

	<message id="functListAccountChooser" text="請選一個下面列出的模式" />
	<message id="functListAccountBanned" text="1 - 已被封鎖帳號 (權限等級 &lt; 0)" />
	<message id="functListAccountPrivileged" text="2 - GM/特權 帳號 (權限等級 &gt; 0)" />
	<message id="functListAccountRegular" text="3 - 一般玩家帳號 (權限等級 = 0)" />
	<message id="functListAccountAll" text="4 - 列出全部" />
	<message id="functListAccountDisplayed" text="您查詢的帳號種類數量: %d" />

	<message id="functAccessLevelUpdated" text="帳號 %s 已經變更完成" />
	<message id="functAccessLevelNotExist" text="帳號 %s 不存在" />

	<message id="functDeleteAccountConfirm" text="您真的要刪除這個帳號? Y/N" />
	<message id="functDeleteAccountAbort" text="略過刪除" />
	<message id="functDeleteAccountCancel" text="放棄刪除" />
	<message id="functDeleteAccountChar" text="進行刪除玩家角色 %s" />
	<message id="functDeleteAccountClan" text="進行刪除血盟 %s" />
	<message id="functDeleteAccountComplete" text="帳號 %s 已被刪除" />
	<message id="functDeleteAccountNotExist" text="帳號 %s 並不存在" />
</localization>

=== Bigcheese/l2adena-l2j-datapack/languages/accountmanager/SQLAccountManager_uk.xml
<?xml version="1.0" encoding="UTF-8"?>
<localization lang="Українська" translator="qwerty13" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="accountmanager.xsd">
	<message id="toolName" text="SQL Менеджер управління обліковими записами" />

	<message id="yesChar" text="т" />
	<message id="noChar" text="н" />
	<message id="trueString" text="True" />
	<message id="falseString" text="False" />

	<message id="functChooser" text="Будь-ласка, оберіть дію" />
	<message id="functCreateAccount" text="1 - Створити новий або поновити існуючий обліковий запис (змінити пароль та рівень доступу)" />
	<message id="functAccessLevel" text="2 - Змінити рівень доступу" />
	<message id="functDeleteAccount" text="3 - Видалити існуючий обліковий запис" />
	<message id="functListAccount" text="4 - Показати облікові записи та рівень доступу" />
	<message id="functExit" text="5 - Вихід" />

	<message id="inputChoice" text="Оберіть" />
	<message id="inputUsername" text="Логін" />
	<message id="inputPassword" text="Пароль" />
	<message id="inputAccessLevel" text="Рівень доступу" />

	<message id="functListAccountChooser" text="Будь-ласка, оберіть режим перегляду" />
	<message id="functListAccountBanned" text="1 - Тільки заблоковані облікові записи (accessLevel &lt; 0)" />
	<message id="functListAccountPrivileged" text="2 - ГМ\привілегії або облікові записи з рівнем доступу (accessLevel &gt; 0)" />
	<message id="functListAccountRegular" text="3 - Облікові записи користувачів (accessLevel = 0)" />
	<message id="functListAccountAll" text="4 - Показати все" />
	<message id="functListAccountDisplayed" text="Відображені облікові записи: %d" />

	<message id="functAccessLevelUpdated" text="Обліковий запис %s був змінений" />
	<message id="functAccessLevelNotExist" text="Обліковий запис %s не існує" />

	<message id="functDeleteAccountConfirm" text="Ви дійсно бажаєте видалити цей обліковий запис? Т/Н" />
	<message id="functDeleteAccountAbort" text="Видалення скасовано" />
	<message id="functDeleteAccountCancel" text="Видалення скасовано" />
	<message id="functDeleteAccountChar" text="Видалення персонажа %s" />
	<message id="functDeleteAccountClan" text="Видалення клану %s" />
	<message id="functDeleteAccountComplete" text="Обліковий запис %s було змінено" />
	<message id="functDeleteAccountNotExist" text="Обліковий запис %s не існує" />
</localization>

=== Bigcheese/l2adena-l2j-datapack/languages/accountmanager/SQLAccountManager_bg.xml
<?xml version="1.0" encoding="UTF-8"?>
<localization lang="български" translator="UnAfraid" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="accountmanager.xsd">
	<message id="toolName" text="Управление на акаунти" />

	<message id="yesChar" text="y" />
	<message id="noChar" text="n" />
	<message id="trueString" text="True" />
	<message id="falseString" text="False" />

	<message id="functChooser" text="Моля изберете опция" />
	<message id="functCreateAccount" text="1 - Създаване или промяна на акаунт (смяна на парола и access level)" />
	<message id="functAccessLevel" text="2 - Промяна на access level" />
	<message id="functDeleteAccount" text="3 - Изтриване на акаунт" />
	<message id="functListAccount" text="4 - Списък с акаунти и access levels" />
	<message id="functExit" text="5 - Изход" />

	<message id="inputChoice" text="Вашият избор" />
	<message id="inputUsername" text="Потребителско име" />
	<message id="inputPassword" text="Парола" />
	<message id="inputAccessLevel" text="Access level" />

	<message id="functListAccountChooser" text="Покажи само акаунтите, които са" />
	<message id="functListAccountBanned" text="1 - Баннати (accessLevel &lt; 0)" />
	<message id="functListAccountPrivileged" text="2 - GM/Привилигировани (accessLevel &gt; 0)" />
	<message id="functListAccountRegular" text="3 - Нормални (accessLevel = 0)" />
	<message id="functListAccountAll" text="4 - Всички" />
	<message id="functListAccountDisplayed" text="Показани акаунти: %d" />

	<message id="functAccessLevelUpdated" text="Акаунтът %s беше променен" />
	<message id="functAccessLevelNotExist" text="Акаунтът %s не съществува" />

	<message id="functDeleteAccountConfirm" text="Желаете ли да изтриете този акаунт? Y/N" />
	<message id="functDeleteAccountAbort" text="Изтриването беше отменено" />
	<message id="functDeleteAccountCancel" text="Изтриването беше отказано" />
	<message id="functDeleteAccountChar" text="Изтриване на герой %s" />
	<message id="functDeleteAccountClan" text="Изтриване на клан %s" />
	<message id="functDeleteAccountComplete" text="Акаунтът %s беше изтрит" />
	<message id="functDeleteAccountNotExist" text="Акаунътъ %s не съществува" />
</localization>
