=== Bigcheese/l2adena-l2j-datapack/data/scripts/quests/Q350_EnhanceYourWeapon/data.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="1">
				<xs:element name="crystal" minOccurs="1" maxOccurs="1">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="1">
							<xs:element name="item" minOccurs="54" maxOccurs="54">
								<xs:complexType>
									<xs:attribute name="itemId" type="xs:positiveInteger" use="required" />
									<xs:attribute name="level" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:integer">
												<xs:minInclusive value="0" />
												<xs:maxInclusive value="17" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="leveledItemId" type="xs:positiveInteger" use="required" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="npc" minOccurs="1" maxOccurs="1">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="1">
							<xs:element name="item" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence minOccurs="1" maxOccurs="1">
										<xs:element name="detail" minOccurs="1" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="absorbType" use="optional">
													<xs:simpleType>
														<xs:restriction base="xs:token">
															<xs:enumeration value="FULL_PARTY" />
															<xs:enumeration value="PARTY_ONE_RANDOM" />
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="chance" use="required">
													<xs:simpleType>
														<xs:restriction base="xs:integer">
															<xs:minInclusive value="1" />
															<xs:maxInclusive value="100" />
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="levelList" use="optional" type="xs:normalizedString" />												<xs:attribute name="maxLevel" use="optional">
													<xs:simpleType>
														<xs:restriction base="xs:integer">
															<xs:minInclusive value="1" />
															<xs:maxInclusive value="9" />
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="skill" type="xs:boolean" use="optional" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="npcId" type="xs:positiveInteger" use="required" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Bigcheese/l2adena-l2j-datapack/data/scripts/quests/Q350_EnhanceYourWeapon/data.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="data.xsd">
	<crystal>
		<item itemId="4629" level="0" leveledItemId="4630" /> <!-- RED 0 - 1 -->
		<item itemId="4630" level="1" leveledItemId="4631" /> <!-- RED 1 - 2 -->
		<item itemId="4631" level="2" leveledItemId="4632" /> <!-- RED 2 - 3 -->
		<item itemId="4632" level="3" leveledItemId="4633" /> <!-- RED 3 - 4 -->
		<item itemId="4633" level="4" leveledItemId="4634" /> <!-- RED 4 - 5 -->
		<item itemId="4634" level="5" leveledItemId="4635" /> <!-- RED 5 - 6 -->
		<item itemId="4635" level="6" leveledItemId="4636" /> <!-- RED 6 - 7 -->
		<item itemId="4636" level="7" leveledItemId="4637" /> <!-- RED 7 - 8 -->
		<item itemId="4637" level="8" leveledItemId="4638" /> <!-- RED 8 - 9 -->
		<item itemId="4638" level="9" leveledItemId="4639" /> <!-- RED 9 - 10 -->
		<item itemId="4639" level="10" leveledItemId="5577" /> <!-- RED 10 - 11 -->
		<item itemId="5577" level="11" leveledItemId="5580" /> <!-- RED 11 - 12 -->
		<item itemId="5580" level="12" leveledItemId="5908" /> <!-- RED 12 - 13 -->
		<item itemId="5908" level="13" leveledItemId="9570" /> <!-- RED 13 - 14 -->
		<item itemId="9570" level="14" leveledItemId="10480" /> <!-- RED 14 - 15 -->
		<item itemId="10480" level="15" leveledItemId="13071" /> <!-- RED 15 - 16 -->
		<item itemId="13071" level="16" leveledItemId="15541" /> <!-- RED 16 - 17 -->
		<item itemId="15541" level="17" leveledItemId="15826" /> <!-- RED 17 - 18 -->

		<item itemId="4640" level="0" leveledItemId="4641" /> <!-- GREEN 0 - 1 -->
		<item itemId="4641" level="1" leveledItemId="4642" /> <!-- GREEN 1 - 2 -->
		<item itemId="4642" level="2" leveledItemId="4643" /> <!-- GREEN 2 - 3 -->
		<item itemId="4643" level="3" leveledItemId="4644" /> <!-- GREEN 3 - 4 -->
		<item itemId="4644" level="4" leveledItemId="4645" /> <!-- GREEN 4 - 5 -->
		<item itemId="4645" level="5" leveledItemId="4646" /> <!-- GREEN 5 - 6 -->
		<item itemId="4646" level="6" leveledItemId="4647" /> <!-- GREEN 6 - 7 -->
		<item itemId="4647" level="7" leveledItemId="4648" /> <!-- GREEN 7 - 8 -->
		<item itemId="4648" level="8" leveledItemId="4649" /> <!-- GREEN 8 - 9 -->
		<item itemId="4649" level="9" leveledItemId="4650" /> <!-- GREEN 9 - 10 -->
		<item itemId="4650" level="10" leveledItemId="5578" /> <!-- GREEN 10 - 11 -->
		<item itemId="5578" level="11" leveledItemId="5581" /> <!-- GREEN 11 - 12 -->
		<item itemId="5581" level="12" leveledItemId="5911" /> <!-- GREEN 12 - 13 -->
		<item itemId="5911" level="13" leveledItemId="9572" /> <!-- GREEN 13 - 14 -->
		<item itemId="9572" level="14" leveledItemId="10482" /> <!-- GREEN 14 - 15 -->
		<item itemId="10482" level="15" leveledItemId="13073" /> <!-- GREEN 15 - 16 -->
		<item itemId="13073" level="16" leveledItemId="15543" /> <!-- GREEN 16 - 17 -->
		<item itemId="15543" level="17" leveledItemId="15828" /> <!-- GREEN 17 - 18 -->

		<item itemId="4651" level="0" leveledItemId="4652" /> <!-- BLUE 0 - 1 -->
		<item itemId="4652" level="1" leveledItemId="4653" /> <!-- BLUE 1 - 2 -->
		<item itemId="4653" level="2" leveledItemId="4654" /> <!-- BLUE 2 - 3 -->
		<item itemId="4654" level="3" leveledItemId="4655" /> <!-- BLUE 3 - 4 -->
		<item itemId="4655" level="4" leveledItemId="4656" /> <!-- BLUE 4 - 5 -->
		<item itemId="4656" level="5" leveledItemId="4657" /> <!-- BLUE 5 - 6 -->
		<item itemId="4657" level="6" leveledItemId="4658" /> <!-- BLUE 6 - 7 -->
		<item itemId="4658" level="7" leveledItemId="4659" /> <!-- BLUE 7 - 8 -->
		<item itemId="4659" level="8" leveledItemId="4660" /> <!-- BLUE 8 - 9 -->
		<item itemId="4660" level="9" leveledItemId="4661" /> <!-- BLUE 9 - 10 -->
		<item itemId="4661" level="10" leveledItemId="5579" /> <!-- BLUE 10 - 11 -->
		<item itemId="5579" level="11" leveledItemId="5582" /> <!-- BLUE 11 - 12 -->
		<item itemId="5582" level="12" leveledItemId="5914" /> <!-- BLUE 12 - 13 -->
		<item itemId="5914" level="13" leveledItemId="9571" /> <!-- BLUE 13 - 14 -->
		<item itemId="9571" level="14" leveledItemId="10481" /> <!-- BLUE 14 - 15 -->
		<item itemId="10481" level="15" leveledItemId="13072" /> <!-- BLUE 15 - 16 -->
		<item itemId="13072" level="16" leveledItemId="15542" /> <!-- BLUE 16 - 17 -->
		<item itemId="15542" level="17" leveledItemId="15827" /> <!-- BLUE 17 - 18 -->
	</crystal>
	<npc>
		<!-- Mobs that level up crystal from Level 1 up to 10 -->
		<item npcId="20583"> <!-- Timak Orc -->
			<detail chance="9" skill="true" maxLevel="1" />
		</item>
		<item npcId="20584"> <!-- Timak Orc Archer -->
			<detail chance="9" skill="true" maxLevel="1" />
		</item>
		<item npcId="20585"> <!-- Timak Orc Soldier -->
			<detail chance="9" skill="true" maxLevel="1" />
		</item>
		<item npcId="20586"> <!-- Timak Orc Warrior -->
			<detail chance="9" skill="true" maxLevel="1" />
		</item>
		<item npcId="20587"> <!-- Timak Orc Shaman -->
			<detail chance="9" skill="true" maxLevel="2" />
		</item>
		<item npcId="20588"> <!-- Timak Orc Overlord -->
			<detail chance="9" skill="true" maxLevel="2" />
		</item>
		<item npcId="20625"> <!-- Malruk Knight -->
			<detail chance="9" skill="true" maxLevel="9" />
		</item>
		<item npcId="20626"> <!-- Malruk Berserker -->
			<detail chance="9" skill="true" maxLevel="9" />
		</item>
		<item npcId="20627"> <!-- Malruk Lord -->
			<detail chance="9" skill="true" maxLevel="9" />
		</item>
		<item npcId="20628"> <!-- Limal Karinness -->
			<detail chance="9" skill="true" maxLevel="9" />
		</item>
		<item npcId="20629"> <!-- Karik -->
			<detail chance="9" skill="true" maxLevel="9" />
		</item>
		<item npcId="20636"> <!-- Forest of Mirrors Ghost -->
			<detail chance="9" skill="true" maxLevel="2" />
		</item>
		<item npcId="20637"> <!-- Forest of Mirrors Ghost -->
			<detail chance="9" skill="true" maxLevel="3" />
		</item>
		<item npcId="20638"> <!-- Forest of Mirrors Ghost -->
			<detail chance="9" skill="true" maxLevel="3" />
		</item>
		<item npcId="20639"> <!-- Mirror -->
			<detail chance="9" skill="true" maxLevel="3" />
		</item>
		<item npcId="20640"> <!-- Harit Lizardman -->
			<detail chance="9" skill="true" maxLevel="4" />
		</item>
		<item npcId="20641"> <!-- Harit Lizardman Grunt -->
			<detail chance="9" skill="true" maxLevel="4" />
		</item>
		<item npcId="20642"> <!-- Harit Lizardman Archer -->
			<detail chance="9" skill="true" maxLevel="4" />
		</item>
		<item npcId="20646"> <!-- Halingka -->
			<detail chance="9" skill="true" maxLevel="5" />
		</item>
		<item npcId="20647"> <!-- Yintzu -->
			<detail chance="9" skill="true" maxLevel="5" />
		</item>
		<item npcId="20648"> <!-- Paliote -->
			<detail chance="9" skill="true" maxLevel="6" />
		</item>
		<item npcId="20649"> <!-- Hamrut -->
			<detail chance="9" skill="true" maxLevel="6" />
		</item>
		<item npcId="20650"> <!-- Kranrot -->
			<detail chance="9" skill="true" maxLevel="7" />
		</item>
		<item npcId="20674"> <!-- Doom Knight -->
			<detail chance="9" skill="true" maxLevel="9" />
		</item>
		<item npcId="20761"> <!-- Pytan -->
			<detail chance="9" skill="true" maxLevel="9" />
		</item>
		<item npcId="20762"> <!-- Pytan Knight -->
			<detail chance="9" skill="true" maxLevel="9" />
		</item>
		<item npcId="20767"> <!-- Timak Orc Troop Leader -->
			<detail chance="9" skill="true" maxLevel="2" />
		</item>
		<item npcId="20768"> <!-- Timak Orc Troop Shaman -->
			<detail chance="9" skill="true" maxLevel="2" />
		</item>
		<item npcId="20769"> <!-- Timak Orc Troop Warrior -->
			<detail chance="9" skill="true" maxLevel="1" />
		</item>
		<item npcId="20770"> <!-- Timak Orc Troop Archer -->
			<detail chance="9" skill="true" maxLevel="1" />
		</item>
		<item npcId="20793"> <!-- Nos -->
			<detail chance="9" skill="true" maxLevel="1" />
		</item>
		<item npcId="20794"> <!-- Blade Stakato -->
			<detail chance="9" skill="true" maxLevel="1" />
		</item>
		<item npcId="20795"> <!-- Blade Stakato Worker -->
			<detail chance="9" skill="true" maxLevel="1" />
		</item>
		<item npcId="20796"> <!-- Blade Stakato Warrior -->
			<detail chance="9" skill="true" maxLevel="1" />
		</item>
		<item npcId="20797"> <!-- Blade Stakato Drone -->
			<detail chance="9" skill="true" maxLevel="2" />
		</item>
		<item npcId="20798"> <!-- Water Giant -->
			<detail chance="9" skill="true" maxLevel="2" />
		</item>
		<item npcId="20799"> <!-- Queen Undine Lad -->
			<detail chance="9" skill="true" maxLevel="2" />
		</item>
		<item npcId="20800"> <!-- Eva's Seeker -->
			<detail chance="9" skill="true" maxLevel="3" />
		</item>
		<item npcId="20801"> <!-- Theeder Piker -->
			<detail chance="9" skill="true" maxLevel="3" />
		</item>
		<item npcId="20802"> <!-- Theeder Mage -->
			<detail chance="9" skill="true" maxLevel="3" />
		</item>
		<item npcId="20803"> <!-- Doll Master -->
			<detail chance="9" skill="true" maxLevel="4" />
		</item>
		<item npcId="20821"> <!-- Erin Ediunce -->
			<detail chance="9" skill="true" maxLevel="9" />
		</item>
		<item npcId="20823"> <!-- Platinum Tribe Soldier -->
			<detail chance="9" skill="true" maxLevel="9" />
		</item>
		<item npcId="20826"> <!-- Platinum Tribe Archer -->
			<detail chance="9" skill="true" maxLevel="9" />
		</item>
		<item npcId="20827"> <!-- Platinum Tribe Warrior -->
			<detail chance="9" skill="true" maxLevel="9" />
		</item>
		<item npcId="20828"> <!-- Platinum Tribe Shaman -->
			<detail chance="9" skill="true" maxLevel="9" />
		</item>
		<item npcId="20829"> <!-- Platinum Tribe Overlord -->
			<detail chance="9" skill="true" maxLevel="9" />
		</item>
		<item npcId="20830"> <!-- Guardian Angel -->
			<detail chance="9" skill="true" maxLevel="9" />
		</item>
		<item npcId="20831"> <!-- Seal Angel -->
			<detail chance="9" skill="true" maxLevel="9" />
		</item>
