=== Bigcheese/l2adena-l2j-datapack/data/dimensionalRift.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="rift">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="1">
				<xs:element name="area" minOccurs="1" maxOccurs="6">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="1">
							<xs:element name="room" minOccurs="1" maxOccurs="9">
								<xs:complexType>
									<xs:sequence minOccurs="1" maxOccurs="1">
										<xs:element name="spawn" minOccurs="1" maxOccurs="3">
											<xs:complexType>
												<xs:attribute name="count" type="xs:positiveInteger" use="required" />
												<xs:attribute name="delay" type="xs:positiveInteger" use="required" />
												<xs:attribute name="mobId" type="xs:positiveInteger" use="required" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="id" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:integer">
												<xs:minInclusive value="1" />
												<xs:maxInclusive value="9" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="type" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:integer">
									<xs:minInclusive value="1" />
									<xs:maxInclusive value="6" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>		</xs:complexType>
	</xs:element>
</xs:schema>

=== Bigcheese/l2adena-l2j-datapack/data/dimensionalRift.xml
<?xml version="1.0" encoding="UTF-8"?>
<rift xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="dimensionalRift.xsd">
	<!-- ########### RECRUITS AREA ########### -->
	<area type="1">
		<room id="1">
			<!-- Otherworldy Invader Soldier -->
			<spawn mobId="21659" count="2" delay="90" />
			<!-- Otherwordly Invader Archer -->
			<spawn mobId="21661" count="4" delay="80" />
			<!-- Otherwordly Invader Soldier -->
			<spawn mobId="21660" count="2" delay="90" />
		</room>
		<room id="2">
			<!-- Otherworldy Invader Priest -->
			<spawn mobId="21664" count="3" delay="90" />
			<!-- Otherwordly Invader Shaman -->
			<spawn mobId="21663" count="2" delay="90" />
			<!-- Otherwordly Invader Elite Soldier -->
			<spawn mobId="21662" count="3" delay="90" />
		</room>
		<room id="3">
			<!-- Otherworldy Invader Martyrs -->
			<spawn mobId="21666" count="2" delay="86" />
			<!-- Otherwordly Invader Warrior -->
			<spawn mobId="21667" count="2" delay="86" />
			<!-- Otherwordly Invader Magus -->
			<spawn mobId="21665" count="2" delay="86" />
		</room>
		<room id="4">
			<!-- Otherworldy Invader Soldier -->
			<spawn mobId="21668" count="2" delay="101" />
			<!-- Otherwordly Invader Discipline -->
			<spawn mobId="21669" count="2" delay="101" />
			<!-- Otherwordly Invader Berserker -->
			<spawn mobId="21670" count="2" delay="101" />
		</room>
		<room id="5">
			<!-- Otherwordly Invader Food -->
			<spawn mobId="18287" count="6" delay="82" />
			<!-- Otherwordly Invader Elite Soldier -->
			<spawn mobId="21672" count="3" delay="82" />
			<!-- Otherwordly Invader Elite Soldier -->
			<spawn mobId="21673" count="3" delay="82" />
		</room>
		<room id="6">
			<!-- Otherworldy Invader Elite Soldier -->
			<spawn mobId="21675" count="4" delay="52" />
			<!-- Otherwordly Invader Warrior -->
			<spawn mobId="21676" count="4" delay="52" />
			<!-- Otherwordly Invader Elite Soldier -->
			<spawn mobId="21674" count="4" delay="52" />
		</room>
		<room id="7">
			<!-- Otherworldy Invader Elite Soldier -->
			<spawn mobId="21677" count="4" delay="100" />
			<!-- Otherwordly Invader Elite Soldier -->
			<spawn mobId="21678" count="4" delay="100" />
			<!-- Otherwordly Invader Food -->
			<spawn mobId="18288" count="4" delay="100" />
		</room>
		<room id="8">
			<!-- Otherworldy Invader Elite Soldier -->
			<spawn mobId="21679" count="4" delay="137" />
			<!-- Otherwordly Invader Magus -->
			<spawn mobId="21681" count="4" delay="137" />
			<!-- Otherwordly Invader Elite Soldier -->
			<spawn mobId="21680" count="4" delay="137" />
		</room>
		<room id="9">
			<!-- Anakazel -->
			<spawn mobId="25333" count="1" delay="600" />
		</room>
	</area>
	<!-- ########### PRIVATES AREA ########### -->
	<area type="2">
		<room id="1">
			<!-- Dimension Invader Soldier -->
			<spawn mobId="21682" count="2" delay="90" />
			<!-- Dimension Invader Archer -->
			<spawn mobId="21684" count="4" delay="80" />
			<!-- Dimension Invader Soldier -->
			<spawn mobId="21683" count="2" delay="90" />
		</room>
		<room id="2">
			<!-- Dimension Invader Priest -->
			<spawn mobId="21687" count="3" delay="90" />
			<!-- Dimension Invader Shaman -->
			<spawn mobId="21686" count="2" delay="90" />
			<!-- Dimension Invader Elite Soldier -->
			<spawn mobId="21685" count="3" delay="90" />
		</room>
		<room id="3">
			<!-- Dimension Invader Martyrs -->
			<spawn mobId="21689" count="2" delay="86" />
			<!-- Dimension Invader Warrior -->
			<spawn mobId="21690" count="2" delay="86" />
			<!-- Dimension Invader Magus -->
			<spawn mobId="21688" count="2" delay="86" />
		</room>
		<room id="4">
			<!-- Dimension Invader Soldier -->
			<spawn mobId="21691" count="2" delay="101" />
			<!-- Dimension Invader Discipline -->
			<spawn mobId="21692" count="2" delay="101" />
			<!-- Dimension Invader Berserker -->
			<spawn mobId="21693" count="2" delay="101" />
		</room>
		<room id="5">
			<!-- Dimension Invader Food -->
			<spawn mobId="18289" count="6" delay="82" />
			<!-- Dimension Invader Elite Soldier -->
			<spawn mobId="21695" count="3" delay="82" />
			<!-- Dimension Invader Elite Soldier -->
			<spawn mobId="21696" count="3" delay="82" />
		</room>
		<room id="6">
			<!-- Dimension Invader Elite Soldier -->
			<spawn mobId="21698" count="4" delay="52" />
			<!-- Dimension Invader Warrior -->
			<spawn mobId="21699" count="4" delay="52" />
			<!-- Dimension Invader Elite Soldier -->
			<spawn mobId="21697" count="4" delay="52" />
		</room>
		<room id="7">
			<!-- Dimension Invader Elite Soldier -->
			<spawn mobId="21700" count="4" delay="100" />
			<!-- Dimension Invader Elite Soldier -->
			<spawn mobId="21701" count="4" delay="100" />
			<!-- Dimension Invader Food -->
			<spawn mobId="18290" count="4" delay="100" />
		</room>
		<room id="8">
			<!-- Dimension Invader Elite Soldier -->
			<spawn mobId="21702" count="4" delay="137" />
			<!-- Dimension Invader Magus -->
			<spawn mobId="21704" count="4" delay="137" />
			<!-- Dimension Invader Elite Soldier -->
			<spawn mobId="21703" count="4" delay="137" />
		</room>
		<room id="9">
			<!-- Anakazel -->
			<spawn mobId="25334" count="1" delay="600" />
		</room>
	</area>
	<!-- ########### OFFICERS AREA ########### -->
	<area type="3">
		<room id="1">
			<!-- Purgatory Invader Soldier -->
			<spawn mobId="21705" count="2" delay="90" />
			<!-- Purgatory Invader Archer -->
			<spawn mobId="21707" count="4" delay="80" />
			<!-- Purgatory Invader Soldier -->
			<spawn mobId="21706" count="2" delay="90" />
		</room>
		<room id="2">
			<!-- Purgatory Invader Priest -->
			<spawn mobId="21710" count="3" delay="90" />
			<!-- Purgatory Invader Shaman -->
			<spawn mobId="21709" count="2" delay="90" />
			<!-- Purgatory Invader Elite Soldier -->
			<spawn mobId="21708" count="3" delay="90" />
		</room>
		<room id="3">
			<!-- Purgatory Invader Martyrs -->
			<spawn mobId="21712" count="2" delay="86" />
			<!-- Purgatory Invader Warrior -->
			<spawn mobId="21713" count="2" delay="86" />
			<!-- Purgatory Invader Magus -->
			<spawn mobId="21711" count="2" delay="86" />
		</room>
		<room id="4">
			<!-- Purgatory Invader Soldier -->
			<spawn mobId="21714" count="2" delay="101" />
			<!-- Purgatory Invader Disciples -->
			<spawn mobId="21715" count="2" delay="101" />
			<!-- Purgatory Invader Berserker -->
			<spawn mobId="21716" count="2" delay="101" />
		</room>
		<room id="5">
			<!-- Purgatory Invader Food -->
			<spawn mobId="18291" count="6" delay="82" />
			<!-- Purgatory Invader Elite Soldier -->
			<spawn mobId="21719" count="3" delay="82" />
			<!-- Purgatory Invader Elite Soldier -->
			<spawn mobId="21718" count="3" delay="82" />
		</room>
		<room id="6">
			<!-- Purgatory Invader Elite Soldier -->
			<spawn mobId="21721" count="4" delay="52" />
			<!-- Purgatory Invader Warrior -->
			<spawn mobId="21722" count="4" delay="52" />
			<!-- Purgatory Invader Elite Soldier -->
			<spawn mobId="21720" count="4" delay="52" />
		</room>
		<room id="7">
			<!-- Purgatory Invader Elite Soldier -->
			<spawn mobId="21723" count="4" delay="100" />
			<!-- Purgatory Invader Elite Soldier -->
			<spawn mobId="21724" count="4" delay="100" />
			<!-- Purgatory Invader Food -->
			<spawn mobId="18292" count="4" delay="100" />
		</room>
		<room id="8">
			<!-- Purgatory Invader Elite Soldier -->
			<spawn mobId="21725" count="4" delay="137" />
			<!-- Purgatory Invader Magus -->
			<spawn mobId="21727" count="4" delay="137" />
			<!-- Purgatory Invader Elite Soldier -->
			<spawn mobId="21726" count="4" delay="137" />
		</room>
		<room id="9">
			<!-- Anakazel -->
			<spawn mobId="25335" count="1" delay="600" />
		</room>
	</area>
	<!-- ########### CAPTAINS AREA ########### -->
	<area type="4">
		<room id="1">
			<!-- Forbidden Path Invader Elite Soldier -->
			<spawn mobId="21728" count="2" delay="90" />
			<!-- Forbidden Path Invader Archer -->
			<spawn mobId="21730" count="4" delay="80" />
			<!-- Forbidden Path Invader Elite Soldier -->
			<spawn mobId="21729" count="2" delay="90" />
		</room>
		<room id="2">
			<!-- Forbidden Path Invader Priest -->
			<spawn mobId="21733" count="3" delay="90" />
			<!-- Forbidden Path Invader Shaman -->
			<spawn mobId="21732" count="2" delay="90" />
			<!-- Forbidden Path Invader Elite Soldier -->
			<spawn mobId="21731" count="3" delay="90" />
		</room>
		<room id="3">
			<!-- Forbidden Path Invader Martyrs -->
			<spawn mobId="21735" count="2" delay="86" />
			<!-- Forbidden Path Invader Warrior -->
			<spawn mobId="21736" count="2" delay="86" />
			<!-- Forbidden Path Invader Magus -->
			<spawn mobId="21734" count="2" delay="86" />
		</room>
		<room id="4">
			<!-- Forbidden Path Invader Soldier -->
			<spawn mobId="21737" count="2" delay="101" />
			<!-- Forbidden Path Invader Disciple -->
			<spawn mobId="21738" count="2" delay="101" />
			<!-- Forbidden Path Invader Berserker -->
			<spawn mobId="21739" count="2" delay="101" />
		</room>
		<room id="5">
			<!-- Forbidden Path Invader Food -->
			<spawn mobId="18293" count="6" delay="82" />
			<!-- Forbidden Path Invader Elite Soldier -->
			<spawn mobId="21741" count="3" delay="82" />
			<!-- Forbidden Path Invader Elite Soldier -->
			<spawn mobId="21742" count="3" delay="82" />
		</room>
		<room id="6">
			<!-- Forbidden Path Invader Elite Soldier -->
			<spawn mobId="21744" count="4" delay="52" />
			<!-- Forbidden Path Invader Warrior -->
			<spawn mobId="21745" count="4" delay="52" />
			<!-- Forbidden Path Invader Elite Soldier -->
			<spawn mobId="21743" count="4" delay="52" />
		</room>
		<room id="7">
			<!-- Forbidden Path Invader Elite Soldier -->
			<spawn mobId="21746" count="4" delay="100" />
