=== Bigcheese/l2adena-l2j-datapack/data/skillTrees/skillTrees.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="1">
				<xs:element name="skillTree" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="1">
							<xs:element name="skill" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="autoGet" type="xs:boolean" use="optional" />
									<xs:attribute name="getLevel" use="optional">
										<xs:simpleType>
											<xs:restriction base="xs:positiveInteger">
												<xs:minInclusive value="1" />
												<xs:maxInclusive value="85" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="itemsIdCount" type="xs:token" use="optional" />
									<xs:attribute name="learnedByFS" type="xs:boolean" use="optional" />
									<xs:attribute name="learnedByNpc" type="xs:boolean" use="optional" />
									<xs:attribute name="levelUpSp" type="xs:nonNegativeInteger" use="optional" />
									<xs:attribute name="preRequisiteSkillIdLvl" type="xs:token" use="optional" />
									<xs:attribute name="race" type="xs:token" use="optional" />
									<xs:attribute name="residenceIds" type="xs:token" use="optional" />
									<xs:attribute name="residenceSkill" type="xs:boolean" use="optional" />
									<xs:attribute name="skillIdLvl" type="xs:token" use="required" />
									<xs:attribute name="skillName" type="xs:normalizedString" use="required" />
									<xs:attribute name="socialClass" use="optional">
										<xs:simpleType>
											<xs:restriction base="xs:nonNegativeInteger">
												<xs:minInclusive value="0" />
												<xs:maxInclusive value="11" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="subClassLvlNumber" type="xs:token" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="classId" use="optional">
							<xs:simpleType>
								<xs:restriction base="xs:nonNegativeInteger">
									<xs:minInclusive value="0" />
									<xs:maxInclusive value="136" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="parentClassId" use="optional">
							<xs:simpleType>
								<xs:restriction base="xs:nonNegativeInteger">
									<xs:minInclusive value="0" />
									<xs:maxInclusive value="136" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="type" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:token">
									<xs:enumeration value="classSkillTree" />
									<xs:enumeration value="collectSkillTree" />
									<xs:enumeration value="fishingSkillTree" />
									<xs:enumeration value="pledgeSkillTree" />
									<xs:enumeration value="subClassSkillTree" />
									<xs:enumeration value="subPledgeSkillTree" />
									<xs:enumeration value="transferSkillTree" />
									<xs:enumeration value="transformSkillTree" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Bigcheese/l2adena-l2j-datapack/data/skillTrees/transformSkillTree.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="skillTrees.xsd">
	<skillTree type="transformSkillTree">
		<!-- Confirmed CT2.5 -->
		<skill skillName="Transform Onyx Beast" skillIdLvl="617,1" getLevel="50" itemsIdCount="9648,1" />
		<skill skillName="Transform Death Blader" skillIdLvl="618,1" getLevel="55" itemsIdCount="9649,1" preRequisiteSkillIdLvl="617,1" />
		<skill skillName="Transform Grail Apostle" skillIdLvl="541,1" getLevel="60" itemsIdCount="9650,1" race="0" preRequisiteSkillIdLvl="617,1" />
		<skill skillName="Transform Grail Apostle" skillIdLvl="542,1" getLevel="60" itemsIdCount="9650,1" race="1;2;3;4" preRequisiteSkillIdLvl="617,1" />
		<skill skillName="Transform Grail Apostle" skillIdLvl="543,1" getLevel="60" itemsIdCount="9650,1" race="5" preRequisiteSkillIdLvl="617,1" />
		<skill skillName="Transform Unicorn" skillIdLvl="544,1" getLevel="60" itemsIdCount="9651,1" race="1" preRequisiteSkillIdLvl="617,1" />
		<skill skillName="Transform Unicorn" skillIdLvl="545,1" getLevel="60" itemsIdCount="9651,1" race="0;5;3;4" preRequisiteSkillIdLvl="617,1" />
		<skill skillName="Transform Unicorn" skillIdLvl="546,1" getLevel="60" itemsIdCount="9651,1" race="2" preRequisiteSkillIdLvl="617,1" />
		<skill skillName="Transform Lilim Knight" skillIdLvl="547,1" getLevel="60" itemsIdCount="9652,1" race="2" preRequisiteSkillIdLvl="617,1" />
		<skill skillName="Transform Lilim Knight" skillIdLvl="548,1" getLevel="60" itemsIdCount="9652,1" race="0;5;3;4" preRequisiteSkillIdLvl="617,1" />
		<skill skillName="Transform Lilim Knight" skillIdLvl="549,1" getLevel="60" itemsIdCount="9652,1" race="1" preRequisiteSkillIdLvl="617,1" />
		<skill skillName="Transform Golem Guardian" skillIdLvl="550,1" getLevel="60" itemsIdCount="9653,1" race="4" preRequisiteSkillIdLvl="617,1" />
		<skill skillName="Transform Golem Guardian" skillIdLvl="551,1" getLevel="60" itemsIdCount="9653,1" race="0;1;2;5" preRequisiteSkillIdLvl="617,1" />
		<skill skillName="Transform Golem Guardian" skillIdLvl="552,1" getLevel="60" itemsIdCount="9653,1" race="3" preRequisiteSkillIdLvl="617,1" />
		<skill skillName="Transform Inferno Drake" skillIdLvl="553,1" getLevel="60" itemsIdCount="9654,1" race="3" preRequisiteSkillIdLvl="617,1" />
		<skill skillName="Transform Inferno Drake" skillIdLvl="554,1" getLevel="60" itemsIdCount="9654,1" race="0;1;2;5" preRequisiteSkillIdLvl="617,1" />
		<skill skillName="Transform Inferno Drake" skillIdLvl="555,1" getLevel="60" itemsIdCount="9654,1" race="4" preRequisiteSkillIdLvl="617,1" />
		<skill skillName="Transform Dragon Bomber" skillIdLvl="556,1" getLevel="60" itemsIdCount="9655,1" race="5" preRequisiteSkillIdLvl="617,1" />
		<skill skillName="Transform Dragon Bomber" skillIdLvl="557,1" getLevel="60" itemsIdCount="9655,1" race="1;2;3;4" preRequisiteSkillIdLvl="617,1" />
		<skill skillName="Transform Dragon Bomber" skillIdLvl="558,1" getLevel="60" itemsIdCount="9655,1" race="0" preRequisiteSkillIdLvl="617,1" />
		<skill skillName="Transform Heretic" skillIdLvl="670,1" getLevel="70" itemsIdCount="10302,1" preRequisiteSkillIdLvl="617,1" />
		<skill skillName="Transform Veil Master" skillIdLvl="671,1" getLevel="70" itemsIdCount="10303,1" preRequisiteSkillIdLvl="617,1" />
		<skill skillName="Transform Saber Tooth Tiger" skillIdLvl="672,1" getLevel="70" itemsIdCount="10304,1" preRequisiteSkillIdLvl="617,1" />
		<skill skillName="Transform Oel Mahum" skillIdLvl="673,1" getLevel="70" itemsIdCount="10305,1" preRequisiteSkillIdLvl="617,1" />
		<skill skillName="Transform Doll Blader" skillIdLvl="674,1" getLevel="70" itemsIdCount="10306,1" preRequisiteSkillIdLvl="617,1" />
		<skill skillName="Transform Zaken" skillIdLvl="663,1" getLevel="60" itemsIdCount="10295,1" preRequisiteSkillIdLvl="617,1" />
		<skill skillName="Transform Anakim" skillIdLvl="664,1" getLevel="70" itemsIdCount="10296,1" preRequisiteSkillIdLvl="617,1" />
		<skill skillName="Transform Venom" skillIdLvl="665,1" getLevel="70" itemsIdCount="10297,1" preRequisiteSkillIdLvl="617,1" />
		<skill skillName="Transform Gordon" skillIdLvl="666,1" getLevel="76" itemsIdCount="10298,1" preRequisiteSkillIdLvl="617,1" />
		<skill skillName="Transform Ranku" skillIdLvl="667,1" getLevel="76" itemsIdCount="10299,1" preRequisiteSkillIdLvl="617,1" />
		<skill skillName="Transform Kechi" skillIdLvl="668,1" getLevel="76" itemsIdCount="10300,1" preRequisiteSkillIdLvl="617,1" />
		<skill skillName="Transform Demon Prince" skillIdLvl="669,1" getLevel="76" itemsIdCount="10301,1" preRequisiteSkillIdLvl="617,1" />
	</skillTree>
</list>
