=== Bigcheese/l2adena-l2j-datapack/data/zones/zones.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="1">
				<xs:element name="zone" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="1">
							<xs:element name="stat" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="name" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:token">
												<xs:enumeration value="affectedLvlMin" />
												<xs:enumeration value="affectedRace" />
												<xs:enumeration value="castleId" />
												<xs:enumeration value="residenceId" />
												<xs:enumeration value="chance" />
												<xs:enumeration value="clanHallId" />
												<xs:enumeration value="EnabledByDefault" />
												<xs:enumeration value="enterMsgId" />
												<xs:enumeration value="fortId" />
												<xs:enumeration value="defaultStatus" />
												<xs:enumeration value="HpRegenBonus" />
												<xs:enumeration value="initialDelay" />
												<xs:enumeration value="instanceId" />
												<xs:enumeration value="InvadeTime" />
												<xs:enumeration value="leaveMsgId" />
												<xs:enumeration value="maxDynamicSkillCount" />
												<xs:enumeration value="move_bonus" />
												<xs:enumeration value="MpRegenBonus" />
												<xs:enumeration value="NoBookmark" />
												<xs:enumeration value="NoItemDrop" />
												<xs:enumeration value="oustX" />
												<xs:enumeration value="oustY" />
												<xs:enumeration value="oustZ" />
												<xs:enumeration value="restartAllowedTime" />
												<xs:enumeration value="restartTime" />
												<xs:enumeration value="reuse" />
												<xs:enumeration value="showDangerIcon" />
												<xs:enumeration value="skillIdLvl" />
												<xs:enumeration value="spawnMaxX" />
												<xs:enumeration value="spawnMaxY" />
												<xs:enumeration value="spawnMaxZ" />
												<xs:enumeration value="spawnMinX" />
												<xs:enumeration value="spawnMinY" />
												<xs:enumeration value="spawnMinZ" />
												<xs:enumeration value="spawnZ" />
												<xs:enumeration value="targetClass" />
												<xs:enumeration value="taxById" />
												<xs:enumeration value="territoryId" />
												<xs:enumeration value="townId" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="val" type="xs:token" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element name="node" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="X" type="xs:integer" use="required" />
									<xs:attribute name="Y" type="xs:integer" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element name="race" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:attribute name="point" type="xs:token" use="required" />
									<xs:attribute name="name" type="xs:token" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element name="spawn" minOccurs="0" maxOccurs="unbounded">
 								<xs:complexType>
									<xs:attribute name="isBanish" type="xs:boolean" use="optional" />
									<xs:attribute name="isChaotic" type="xs:boolean" use="optional" />
									<xs:attribute name="isOther" type="xs:boolean" use="optional" />
									<xs:attribute name="X" type="xs:integer" use="required" />
									<xs:attribute name="Y" type="xs:integer" use="required" />
									<xs:attribute name="Z" type="xs:integer" use="required" />
 								</xs:complexType>
 							</xs:element>
						</xs:sequence>
						<xs:attribute name="id" type="xs:positiveInteger" use="optional" />
						<xs:attribute name="maxZ" type="xs:integer" use="required" />
						<xs:attribute name="minZ" type="xs:integer" use="required" />
						<xs:attribute name="name" type="xs:normalizedString" use="required" />
						<xs:attribute name="rad" type="xs:positiveInteger" use="optional" />
						<xs:attribute name="shape" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:token">
									<xs:enumeration value="Cuboid" />
									<xs:enumeration value="Cylinder" />
									<xs:enumeration value="NPoly" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="type" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:token">
									<xs:enumeration value="ArenaZone" />
									<xs:enumeration value="BossZone" />
									<xs:enumeration value="CastleZone" />
									<xs:enumeration value="ClanHallZone" />
									<xs:enumeration value="ConditionZone" />
									<xs:enumeration value="DamageZone" />
									<xs:enumeration value="DerbyTrackZone" />
									<xs:enumeration value="EffectZone" />
									<xs:enumeration value="FishingZone" />
									<xs:enumeration value="FortZone" />
									<xs:enumeration value="HQZone" />
									<xs:enumeration value="JailZone" />
									<xs:enumeration value="LandingZone" />
									<xs:enumeration value="MotherTreeZone" />
									<xs:enumeration value="NoDropItemZone" />
									<xs:enumeration value="NoHqZone" />
									<xs:enumeration value="NoLandingZone" />
									<xs:enumeration value="NoRestartZone" />
									<xs:enumeration value="NoStoreZone" />
									<xs:enumeration value="NoSummonFriendZone" />
									<xs:enumeration value="OlympiadStadiumZone" />
									<xs:enumeration value="PeaceZone" />
									<xs:enumeration value="ResidenceTeleportZone" />
									<xs:enumeration value="RespawnZone" />
									<xs:enumeration value="ScriptZone" />
									<xs:enumeration value="SiegeZone" />
									<xs:enumeration value="SwampZone" />
									<xs:enumeration value="TerritoryWarZone" />
									<xs:enumeration value="TownZone" />
									<xs:enumeration value="WaterZone" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="enabled" type="xs:boolean" use="required" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Bigcheese/l2adena-l2j-datapack/data/zones/custom_script_zones.xml
<?xml version="1.0" encoding="UTF-8"?>
<list enabled="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="zones.xsd">
	<!-- Custom Script Zones -->
	<zone name="Emerald Square 1st Secret Room" id="20105" type="ScriptZone" shape="Cuboid" minZ="-11900" maxZ="-11800">
		<node X="144175" Y="142396" />
		<node X="144251" Y="142588" />
	</zone>
	<zone name="Emerald Square 2nd Secret Room" id="20106" type="ScriptZone" shape="Cuboid" minZ="-12250" maxZ="-12150">
		<node X="147400" Y="143631" />
		<node X="147484" Y="143828" />
	</zone>
	<zone name="Emerald Square 3rd Secret Room" id="20107" type="ScriptZone" shape="Cuboid" minZ="-12150" maxZ="-12000">
		<node X="149396" Y="143473" />
		<node X="149559" Y="143584" />
	</zone>
	<zone name="Pailaka (Forgotten Temple)" id="20108" type="ScriptZone" shape="NPoly" minZ="-5050" maxZ="-3900">
		<node X="-62840" Y="178808" />
		<node X="-62840" Y="184568" />
		<node X="-60792" Y="184568" />
		<node X="-60792" Y="188792" />
		<node X="-57976" Y="191224" />
		<node X="-53000" Y="190840" />
		<node X="-52360" Y="190200" />
		<node X="-52360" Y="178808" />
	</zone>
	<zone name="Pailaka (Devil's Isle)" id="20109" type="ScriptZone" shape="NPoly" minZ="-3770" maxZ="-3700">
		<node X="76650" Y="-221310" />
		<node X="76630" Y="-221880" />
		<node X="75490" Y="-221480" />
		<node X="75630" Y="-221140" />
	</zone>
	<zone name="Nornil's Garden Warrior's Gate" id="20110" type="ScriptZone" shape="Cuboid" minZ="-12650" maxZ="-12600">
		<node X="-109864" Y="76184" />
		<node X="-109544" Y="76392" />
	</zone>
	<zone name="Nornil's Garden Midway Gate" id="20111" type="ScriptZone" shape="Cuboid" minZ="-12930" maxZ="-12900">
		<node X="-107560" Y="80488" />
		<node X="-107240" Y="80808" />
	</zone>
	<zone name="Nornil's Garden Gate" id="20112" type="ScriptZone" shape="Cuboid" minZ="-12990" maxZ="-12960">
		<node X="-111016" Y="83944" />
		<node X="-110696" Y="84264" />
	</zone>
	<zone name="Pagans mark" id="30100" type="ScriptZone" shape="NPoly" minZ="-10735" maxZ="-10720">
		<node X="-16100" Y="-36620" />
		<node X="-16600" Y="-36620" />
		<node X="-16600" Y="-36925" />
		<node X="-16100" Y="-36925" />
	</zone>
	<zone name="Hellbound" id="40101" type="ScriptZone" shape="NPoly" minZ="-30000" maxZ="30000">
		<node X="-32768" Y="229376" />
		<node X="32768" Y="229376" />
		<node X="32768" Y="262143" />
		<node X="-32768" Y="262143" />
	</zone>
	<zone name="Seed of Infinity AirShips dock" id="50600" type="ScriptZone" shape="Cylinder" minZ="-1000" maxZ="6200" rad="2900">
		<node X="-212855" Y="209819" />
	</zone>
	<zone name="Seed of Destruction AirShips dock" id="50601" type="ScriptZone" shape="Cylinder" minZ="-1000" maxZ="6200" rad="4300">
		<node X="-249460" Y="249282" />
	</zone>
	<zone name="Keucereus Base North" id="50602" type="ScriptZone" shape="NPoly" minZ="-1000" maxZ="6200">
		<node X="-193315" Y="240184" />
		<node X="-188053" Y="235278" />
		<node X="-179811" Y="238353" />
		<node X="-178407" Y="242454" />
		<node X="-178685" Y="244665" />
	</zone>
	<zone name="Keucereus Base South" id="50603" type="ScriptZone" shape="NPoly" minZ="-1000" maxZ="6200">
		<node X="-178685" Y="244664" />
		<node X="-180120" Y="246779" />
		<node X="-185598" Y="249572" />
		<node X="-193009" Y="245647" />
		<node X="-193315" Y="240185" />
	</zone>
	<zone name="Seed of Annihilation 1" id="60002" type="ScriptZone" shape="Cylinder" minZ="-10600" maxZ="-10500" rad="260">
		<node X="-182488" Y="186655" />
	</zone>
	<zone name="Seed of Annihilation 2" id="60003" type="ScriptZone" shape="Cylinder" minZ="-11050" maxZ="-10950" rad="260">
		<node X="-212755" Y="184380" />
	</zone>
	<zone name="Seed of Annihilation 3" id="60004" type="ScriptZone" shape="Cylinder" minZ="-10800" maxZ="-10700" rad="360">
		<node X="-178458" Y="188167" />
	</zone>
	<zone name="Seed of Annihilation 4" id="60005" type="ScriptZone" shape="Cylinder" minZ="-15250" maxZ="-15100" rad="360">
		<node X="-179430" Y="183844" />
	</zone>
	<zone name="Seed of Destruction" id="60009" type="ScriptZone" shape="Cuboid" minZ="-14065" maxZ="-6500">
		<node X="-237600" Y="221168" />
		<node X="-253900" Y="204849" />
	</zone>
</list>

=== Bigcheese/l2adena-l2j-datapack/data/zones/h5_olympiad_stadium_zones.xml
<?xml version="1.0" encoding="UTF-8"?>
<list enabled="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="zones.xsd">
	<!-- H5 Olympiad Stadium Zones -->
	<zone name="Grassy Arena" type="OlympiadStadiumZone" shape="Cylinder" minZ="-3351" maxZ="1149" rad="2000">
		<node X="-88082" Y="-252843" />
		<!-- point1 -->
		<spawn X="-89485" Y="-252843" Z="-3341" />
		<spawn X="-89500" Y="-252843" Z="-3341" />
		<spawn X="-89515" Y="-252843" Z="-3341" />
		<!-- point2 -->
		<spawn X="-86678" Y="-252843" Z="-3341" />
		<spawn X="-86663" Y="-252843" Z="-3341" />
		<spawn X="-86648" Y="-252843" Z="-3341" />
	</zone>
	<zone name="Three Bridges Arena" type="OlympiadStadiumZone" shape="Cylinder" minZ="-7751" maxZ="-3251" rad="2000">
		<node X="-75465" Y="-252461" />
		<!-- point1 -->
		<spawn X="-76845" Y="-252461" Z="-7741" />
		<spawn X="-76860" Y="-252461" Z="-7741" />
		<spawn X="-76875" Y="-252461" Z="-7741" />
		<!-- point2 -->
		<spawn X="-74085" Y="-252461" Z="-7741" />
		<spawn X="-74070" Y="-252461" Z="-7741" />
		<spawn X="-74055" Y="-252461" Z="-7741" />
	</zone>
	<zone name="Heros's Vestiges Arena" type="OlympiadStadiumZone" shape="Cylinder" minZ="-8485" maxZ="-3985" rad="2000">
		<node X="-88095" Y="-239351" />
		<!-- point1 -->
		<spawn X="-89277" Y="-239351" Z="-8475" />
		<spawn X="-89292" Y="-239351" Z="-8475" />
		<spawn X="-89307" Y="-239351" Z="-8475" />
		<!-- point2 -->
		<spawn X="-86913" Y="-239351" Z="-8475" />
		<spawn X="-86898" Y="-239351" Z="-8475" />
		<spawn X="-86883" Y="-239351" Z="-8475" />
	</zone>
	<zone name="Orbis Arena" type="OlympiadStadiumZone" shape="Cylinder" minZ="-8228" maxZ="-3728" rad="2000">
		<node X="-75457" Y="-239182" />
		<!-- point1 -->
		<spawn X="-76460" Y="-239182" Z="-8218" />
		<spawn X="-76475" Y="-239182" Z="-8218" />
		<spawn X="-76490" Y="-239182" Z="-8218" />
		<!-- point2 -->
		<spawn X="-74173" Y="-239182" Z="-8218" />
		<spawn X="-74158" Y="-239182" Z="-8218" />
		<spawn X="-74143" Y="-239182" Z="-8218" />
	</zone>
</list>
